project/config/routes.rb
Rails.application.routes.draw do
  resources :records
  get 'welcome/index'
root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

project/app/models/record.rb
class Record < ApplicationRecord
end

project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

project/app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:show, :edit, :update, :destroy]

  # GET /records
  # GET /records.json
  def index
    @records = Record.all
  end

  # GET /records/1
  # GET /records/1.json
  def show
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params)

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: 'Record was successfully created.' }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit(:title, :genre, :link)
    end
end

project/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

project/app/helpers/application_helper.rb
module ApplicationHelper
end

project/app/helpers/records_helper.rb
module RecordsHelper
end

project/app/helpers/welcome_helper.rb
module WelcomeHelper
end

project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

project/app/views/records/_form.html.erb
<%= form_for(record) do |f| %>
  <% if record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :genre %>
    <%= f.text_field :genre %>
  </div>

  <div class="field">
    <%= f.label :link %>
    <%= f.text_field :link %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

project/app/views/records/edit.html.erb
<h1>Editing Record</h1>

<%= render 'form', record: @record %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

project/app/views/records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List of songs</h1>

<table>
  <thead>
    <tr>
      <th>Song</th>
      <th>Genre</th>
      <th>Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @records.each do |record| %>
      <tr>
        <td><%= record.title %></td>
        <td><%= record.genre %></td>
        <td><%= record.link %></td>
        <td><%= link_to 'Show', record %></td>
        <td><%= link_to 'Edit', edit_record_path(record) %></td>
        <td><%= link_to 'Destroy', record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Submit a new song', new_record_path %>
<div></div>
<%= link_to 'Back to Home', controller: 'welcome' %>

project/app/views/records/new.html.erb
<h1>New Song</h1>

<%= render 'form', record: @record %>

<%= link_to 'Back', records_path %>

project/app/views/records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @record.title %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @record.genre %>
</p>

<p>
  <strong>Link:</strong>
  <%= @record.link %>
</p>

<%= link_to 'Edit', edit_record_path(@record) %> |
<%= link_to 'Back', records_path %>

project/app/views/welcome/index.html.erb
<!DOCTYPE html>
<!--[if IE 9]><html class="lt-ie10" lang="en" > <![endif]-->
<html class="no-js" lang="en">
<head>
<meta charset="utf-8">

<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Foundation 5</title>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/5.5.3/css/normalize.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/5.5.3/css/foundation.min.css">
<link href="https://cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css" rel='stylesheet' type='text/css'>

<script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>
<style>
body  {
    background-image: url("https://media.giphy.com/media/xTiTnxpQ3ghPiB2Hp6/giphy.gif");

}
</style>
</head>
<body>

<a href="http://zurb.com/article/1469/foundation-building-blocks-over-100-compo" class="grid-banner">
</a>

<script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-2195009-2', 'auto');
      ga('send', 'pageview');

      ga('create', 'UA-2195009-27', 'auto', {name: "foundation"});
      ga('foundation.send', 'pageview');

    </script>
<div class="row">
<div class="large-12 columns">

<nav class="top-bar" data-topbar>
<ul class="title-area">

<div class="hide-for-small">
<div id="featured"><img alt="slide image" src="http://www.hdwallpapersfreedownload.com/uploads/large/3d-and-abstract/red-abstract-wallpapers.jpg"></div>

</div>

<div class="row">
<div class="small-12 show-for-small"><br>
<img src="https://placehold.it/1000x600&amp;text=For%20Small%20Screens"></div>
</div>
</div>
</div><br>
<div class="row">
<div class="large-12 columns">
<div class="row">


<div class="large-3 small-6 columns">

<iframe width="225" height="150" src="https://www.youtube.com/embed/xrbrQhpvn8E" frameborder="0" allowfullscreen></iframe>
<h6 class="panel">This youtube video contains a 24/7 live stream radio that plays relaxing music.</h6>
</div>
<div class="large-3 small-6 columns">
<iframe src="https://embed.spotify.com/?uri=spotify%3Auser%3A1247863031%3Aplaylist%3A4sBk0ujtbmkmfbkMH18fGl" width="225" height="150" frameborder="0" allowtransparency="true"></iframe>
<h6 class="panel">Click on this spotify playlist to listen to a selection of music in the rock genre.</h6>
</div>
<div class="large-3 small-6 columns">
<iframe src="https://embed.spotify.com/?uri=spotify%3Auser%3Aspotify%3Aplaylist%3A37i9dQZF1DX0BcQWzuB7ZO" width="225" height="150" frameborder="0" allowtransparency="true"></iframe>
<h6 class="panel">This playlist contains music best suited for dancing. Volume warning!</h6>
</div>
<div class="large-3 small-6 columns">
<iframe src="https://embed.spotify.com/?uri=spotify%3Auser%3Aspotify%3Aplaylist%3A37i9dQZF1DX4sWSpwq3LiO" width="225" height="150" frameborder="0" allowtransparency="true"></iframe>
<h6 class="panel">This playlist contains soothing piano music. Don't fall asleep yet. </h6>
</div>
</div>
</div>
</div>
<div class="row">
<div class="large-12 columns">
<div class="row">

<div class="large-8 columns">
<div class="panel radius">
<div class="row">
<div class="large-6 small-6 columns">
<h4>What does this website do?</h4>
<hr>
<h5 class="subheader">This website's sole purpose is to share all kinds of music.</h5>
<h4> Got something to share?
<%= link_to 'Share it here', new_record_path %></h5>
<footer class="row">
<div class="large-12 columns">
<hr>
<div class="row">
<div class="large-6 columns">
<p>© Copyright E.Liao 2017</p>
</div>
<div class="large-6 columns">
<ul class="inline-list right">
</ul>
</div>
</div>
</div>
</footer>
<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/5.5.3/js/foundation.min.js"></script>
<script>
      $(document).foundation();
    </script>
<script type="text/javascript" src="https://intercom.zurb.com/scripts/zcom.js"></script>
</body>
</html>